server:
  port: 3020
spring:
  ai:
    openai:
      api-key: hk-yknnba1000052208028da3f549fe579bb97f9ffd82fdf5c2
      base-url: https://api.openai-hk.com
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        enabled: true
  datasource:
    username: root
    password: wpl20040217
    url: jdbc:mysql://localhost:3306/wpl_code?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 810220955@qq.com
    password: yfibxqenfejqbcje
    default-encoding: utf-8
    ssl:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8