server:
  port: 3020
spring:
  datasource:
    username: root
    password: wpl20040217
    url: jdbc:mysql://localhost:3306/wpl_code?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 810220955@qq.com
    password: abkpgozuoxfgbdhj
    default-encoding: utf-8
    ssl:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379